{
    "status": "Fix Released", 
    "last_updated": "2012-04-05 09:51:01.688185+00:00", 
    "description": "\nIn nova/api/ec2/cloud.py, rescue_instance cannot work. It currently passes an instance id to compute api rescue function, but that expects an instance object.", 
    "tags": [
        "ec2"
    ], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/899225", 
    "owner": "https://api.launchpad.net/1.0/~alex-meade", 
    "id": 899225, 
    "index": 3674, 
    "openned": "2011-12-02 15:41:19.590250+00:00", 
    "created": "2011-12-02 15:41:19.590250+00:00", 
    "title": "EC2API: rescue instance can't work", 
    "comments": [
        {
            "content": "\nIn nova/api/ec2/cloud.py, rescue_instance cannot work. It currently passes an instance id to compute api rescue function, but that expects an instance object.", 
            "date_created": "2011-12-02 15:41:19.590250+00:00", 
            "author": "https://api.launchpad.net/1.0/~alex-meade"
        }, 
        {
            "content": "Same goes for unrescue_instance", 
            "date_created": "2011-12-02 15:42:41.999804+00:00", 
            "author": "https://api.launchpad.net/1.0/~alex-meade"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/2042\nCommitted: http://github.com/openstack/nova/commit/91cfa62b4a09cafa8af0772c68d36de9216dc440\nSubmitter: Jenkins\nBranch:    master\n\n status fixcommitted\n done\n\ncommit 91cfa62b4a09cafa8af0772c68d36de9216dc440\nAuthor: Alex Meade <email address hidden>\nDate:   Fri Dec 2 11:36:38 2011 -0500\n\n    EC2 rescue/unrescue is broken, bug 899225\n    \n    Change-Id: I5a0b9c08a43e8c606d1c885cf7f47382fa4664a8\n", 
            "date_created": "2011-12-05 19:02:37+00:00", 
            "author": "https://api.launchpad.net/1.0/~openstack-gerrit"
        }
    ], 
    "closed": "2011-12-14 09:56:18.552058+00:00"
}