{
    "status": "Invalid", 
    "last_updated": "2012-07-12 13:28:42.479641+00:00", 
    "description": "During a fresh install on Ubuntu 12.04 Server, the nova-manage utility nearly always throws up the following error:\n\nDEBUG nova.utils [req-977fa436-86ce-4dc5-9b8b-461dcef45fb9 None None] backend <module 'nova.db.sqlalchemy.api' from '/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.pyc'> from (pid=15952) __get_backend /usr/lib/python2.7/dist-packages/nova/utils.py:658\n\nAll updates have been installed and the first instance of this problem occurred while going through the Openstack Install and Deploy Manual from docs.openstack.org, Section 5, Configuring the Database for Compute. The command \"sudo nova-manage db sync\" was where I first saw this error; subsequent attempts to use the command produced the same error with the following categories:\n\nnova-manage agent list\nnova-manage account list\nnova-manage db version\nnova-manage db sync\nnova-manage flavor list\nnova-manage network list\nnova-manage network create\n\nI assume that there are others that will produce this same result. I also have devstack installed on a VM (VMware Fusion, v4.1.2) running Ubuntu 12.04 Server that has a similar problem:\n\nDEBUG nova.utils [req-18488497-984a-4853-bb68-e3bb441e43c5 None None] backend <module 'nova.db.sqlalchemy.api' from '/opt/stack/nova/nova/db/sqlalchemy/api.pyc'> from (pid=2863) __get_backend /opt/stack/nova/nova/utils.py:569\n\nThis was one of the errors that came up from the command \"nova-manage -v service list.\" Most of the other nova-manage commands on that machine state that the table does not exist. \n\nThe devstack install is using OpenStack version 2012.2-dev (2012.2-LOCALBRANCH:LOCALREVISION).\nThe main install is using OpenStack version 2012.1 (2012.1-LOCALBRANCH:LOCALREVISION). \n\nLet me know what other information you need.", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 18, 
    "link": "https://bugs.launchpad.net/nova/+bug/1009649", 
    "owner": "None", 
    "id": 1009649, 
    "index": 4132, 
    "openned": "2012-06-06 18:17:51.964511+00:00", 
    "created": "2012-06-06 18:17:51.964511+00:00", 
    "title": "nova-manage operations fail during install", 
    "comments": [
        {
            "content": "During a fresh install on Ubuntu 12.04 Server, the nova-manage utility nearly always throws up the following error:\n\nDEBUG nova.utils [req-977fa436-86ce-4dc5-9b8b-461dcef45fb9 None None] backend <module 'nova.db.sqlalchemy.api' from '/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/api.pyc'> from (pid=15952) __get_backend /usr/lib/python2.7/dist-packages/nova/utils.py:658\n\nAll updates have been installed and the first instance of this problem occurred while going through the Openstack Install and Deploy Manual from docs.openstack.org, Section 5, Configuring the Database for Compute. The command \"sudo nova-manage db sync\" was where I first saw this error; subsequent attempts to use the command produced the same error with the following categories:\n\nnova-manage agent list\nnova-manage account list\nnova-manage db version\nnova-manage db sync\nnova-manage flavor list\nnova-manage network list\nnova-manage network create\n\nI assume that there are others that will produce this same result. I also have devstack installed on a VM (VMware Fusion, v4.1.2) running Ubuntu 12.04 Server that has a similar problem:\n\nDEBUG nova.utils [req-18488497-984a-4853-bb68-e3bb441e43c5 None None] backend <module 'nova.db.sqlalchemy.api' from '/opt/stack/nova/nova/db/sqlalchemy/api.pyc'> from (pid=2863) __get_backend /opt/stack/nova/nova/utils.py:569\n\nThis was one of the errors that came up from the command \"nova-manage -v service list.\" Most of the other nova-manage commands on that machine state that the table does not exist. \n\nThe devstack install is using OpenStack version 2012.2-dev (2012.2-LOCALBRANCH:LOCALREVISION).\nThe main install is using OpenStack version 2012.1 (2012.1-LOCALBRANCH:LOCALREVISION). \n\nLet me know what other information you need.", 
            "date_created": "2012-06-06 18:17:51.964511+00:00", 
            "author": "https://api.launchpad.net/1.0/~jdiegoavalos"
        }, 
        {
            "content": "That is a debug message and doesn't illustrate an error.  If you do nova-manage db sync and then run other nova-manage commands they should work.\n\nIf not, please check /etc/nova/nova/nova-manage.log and report if there is any info there.", 
            "date_created": "2012-06-06 18:37:10.724358+00:00", 
            "author": "https://api.launchpad.net/1.0/~vishvananda"
        }, 
        {
            "content": "The debug message is the output of the command nova-manage db sync. The next step in the document is to list the services using nova-manage -v services list. That command produced the same debug output and listed no services, but the header did appear. As it turns out, the services table of the nova database is empty. I tried to the nova-manage network command just to see what would happen; it also produced that debug output, but it at least put entries in the network table of the nova database. How can I verify that the services are working? And why is the nova-manage not entering all information into the nova database?\n\nPlease let me know if I'm doing something wrong, as that is entirely possible. But every debug statement points back to a line in the LazyPluggle(object) class; is this just a red herring?\n\nWhile both the nova-manage db sync and nova-manage -v service list both produced the debug output, neither made fresh entries into the nova-manage.log. ", 
            "date_created": "2012-06-06 19:04:46.488959+00:00", 
            "author": "https://api.launchpad.net/1.0/~jdiegoavalos"
        }, 
        {
            "content": "Red herring.  You shouldn't see any services show up until you actually run some services.  If you have services running and you don't see them in the database, then it sounds like you may have your services connecting to a different database somehow (perhaps a bad setting for sql_connecton).", 
            "date_created": "2012-06-06 20:33:27+00:00", 
            "author": "https://api.launchpad.net/1.0/~vishvananda"
        }, 
        {
            "content": "Made the other a duplicate of this bug as vishy already responded here.", 
            "date_created": "2012-06-07 14:18:15.096567+00:00", 
            "author": "https://api.launchpad.net/1.0/~bcwaldon"
        }, 
        {
            "content": "I had exactly the same problem yesterday when I was installing Openstack from scratch according to Openstack Install and Deploy Manual from docs.openstack.org, Section 5, as well.\n\nI created an Ubuntu 12.04 server on rackspace public cloud and installed Openstack on it. Everything was fine without any problem until I entered \"nova-manage db sync\". I logged in as a root, so no \"sudo\". Then there are exact the same behaviors as Jason's.\n\nI didn't figure out why. So I restored to an image I created at the point before installing nova (P36 in the manual). I started from then, and noticed that the log message occurred for the first time when issuing \"apt-get install nova-compute nova-volume nova-vncproxy nova-api nova-ajax-console-proxy nova-cert nova-consoleauth nova-doc nova-scheduler nova-network\". \n\nHere is some of the output of that command.\n\n============================================================================\nSetting up gawk (1:3.1.8+dfsg-0.1ubuntu1) ...\nSetting up libaio1 (0.3.109-2ubuntu1) ...\nSetting up libasound2 (1.0.25-1ubuntu10.1) ...\nSetting up libasyncns0 (0.8-4) ...\nSetting up libavahi-common-data (0.6.30-5ubuntu2) ...\nSetting up libavahi-common3 (0.6.30-5ubuntu2) ...\nSetting up libavahi-client3 (0.6.30-5ubuntu2) ...\nSetting up libcaca0 (0.99.beta17-2.1ubuntu2) ...\nSetting up libogg0 (1.2.2~dfsg-1ubuntu1) ...\nSetting up libflac8 (1.2.1-6) ...\nSetting up libnspr4 (4.8.9-1ubuntu2) ...\nSetting up libnss3 (3.13.1.with.ckbi.1.88-1ubuntu6) ...\nSetting up libjson0 (0.9-1ubuntu1) ...\nSetting up libvorbis0a (1.3.2-1ubuntu3) ...\nSetting up libvorbisenc2 (1.3.2-1ubuntu3) ...\nSetting up libsndfile1 (1.0.25-4) ...\nSetting up libpulse0 (1:1.1-0ubuntu15.1) ...\nSetting up libsdl1.2debian (1.2.14-6.4ubuntu3) ...\nSetting up python-m2crypto (0.21.1-2ubuntu2) ...\nSetting up seabios (0.6.2-0ubuntu2.1) ...\nSetting up vgabios (0.6c-2ubuntu3) ...\nSetting up qemu-common (1.0+noroms-0ubuntu13) ...\nSetting up librados2 (0.41-1ubuntu2) ...\nSetting up librbd1 (0.41-1ubuntu2) ...\nSetting up qemu-utils (1.0+noroms-0ubuntu13) ...\nSetting up qemu-kvm (1.0+noroms-0ubuntu13) ...\nqemu-kvm start/running\nSetting up libyajl1 (1.0.12-2) ...\nSetting up libnetfilter-conntrack3 (0.9.1-1ubuntu1) ...\nSetting up dnsmasq-base (2.59-4) ...\nSetting up dnsmasq-utils (2.59-4) ...\nSetting up ebtables (2.0.9.2-2ubuntu2) ...\nSetting up libsysfs2 (2.1.0+repack-1) ...\nSetting up iputils-arping (3:20101006-1ubuntu1) ...\nSetting up kvm (1:84+dfsg-0ubuntu16+1.0+noroms+0ubuntu13) ...\nSetting up kvm-ipxe (1.0.0+git-3.55f6c88-0ubuntu1) ...\nSetting up libapparmor1 (2.7.102-0ubuntu3.1) ...\nSetting up libconfig-general-perl (2.50-1) ...\nSetting up libdevmapper-event1.02.1 (2:1.02.48-4ubuntu7.1) ...\nSetting up libnuma1 (2.0.8~rc3-1) ...\nSetting up libsgutils2-2 (1.33-1) ...\nSetting up libtidy-0.99-0 (20091223cvs-1ubuntu2) ...\nSetting up libxenstore3.0 (4.1.2-2ubuntu2) ...\nSetting up libvirt0 (0.9.8-2ubuntu17.1) ...\nSetting up cgroup-lite (1.1) ...\ncgroup-lite start/running\nSetting up libvirt-bin (0.9.8-2ubuntu17.1) ...\nAdding group `libvirtd' (GID 119) ...\nDone.\nlibvirt-bin start/running, process 10286\nSetting up libxml2-utils (2.7.8.dfsg-5.1ubuntu4.1) ...\nSetting up watershed (6) ...\nupdate-initramfs: deferring update (trigger activated)\nSetting up lvm2 (2.02.66-4ubuntu7.1) ...\nupdate-initramfs: deferring update (trigger activated)\nSetting up open-iscsi-utils (2.0.871-0ubuntu9) ...\nSetting up open-iscsi (2.0.871-0ubuntu9) ...\nupdate-rc.d: warning: open-iscsi stop runlevel arguments (0 1 6) do not match LSB Default-Stop values (0 6)\n * Starting iSCSI initiator service iscsid                                                                                                 [ OK ]\n * Setting up iSCSI targets                                                                                                                [ OK ]\nSetting up python-boto (2.2.2-0ubuntu2) ...\nSetting up python-carrot (0.10.7-1ubuntu1) ...\nSetting up python-cheetah (2.4.4-2ubuntu3) ...\nSetting up python-lockfile (1:0.8-2ubuntu1) ...\nSetting up python-daemon (1.5.5-1ubuntu1) ...\nSetting up python-dingus (0.3.2-1ubuntu1) ...\nSetting up python-feedparser (5.1-0ubuntu3.1) ...\nSetting up python-gflags (1.5.1-1build1) ...\nSetting up python-ldap (2.3.13-1build1) ...\nSetting up python-libvirt (0.9.8-2ubuntu17.1) ...\nSetting up python-libxml2 (2.7.8.dfsg-5.1ubuntu4.1) ...\nSetting up python-netaddr (0.7.5-4build2) ...\nSetting up python-nose (1.1.2-3) ...\nSetting up python-novaclient (2012.1-0ubuntu1) ...\nSetting up python-stompy (0.2.9-1ubuntu1) ...\nSetting up python-suds (0.4.1-2ubuntu1) ...\nSetting up python-utidylib (0.2-8build1) ...\nSetting up sg3-utils (1.33-1) ...\nSetting up libibverbs1 (1.1.5-1ubuntu1) ...\nSetting up librdmacm1 (1.0.14.1-2) ...\nSetting up tgt (1:1.0.17-1ubuntu2) ...\ntgt start/running, process 10615\nSetting up kpartx (0.4.9-3ubuntu5) ...\nSetting up nova-ajax-console-proxy (2012.1-0ubuntu2.3) ...\nSetting up python-pycurl (7.19.0-4ubuntu3) ...\nSetting up python-nova (2012.1-0ubuntu2.3) ...\nSetting up nova-common (2012.1-0ubuntu2.3) ...\nAdding system user `nova' (UID 112) ...\nAdding new user `nova' (UID 112) with group `nova' ...\nNot creating home directory `/var/lib/nova'.\nusermod: no changes\n2012-06-15 13:00:35 DEBUG nova.utils [-] backend <module 'nova.db.sqlalchemy.migration' from '/usr/lib/python2.7/dist-packages/nova/db/sqlalchemy/migration.pyc'> from (pid=10676) __get_backend /usr/lib/python2.7/dist-packages/nova/utils.py:658\nSetting up nova-api (2012.1-0ubuntu2.3) ...\nnova-api start/running, process 10717\nSetting up nova-cert (2012.1-0ubuntu2.3) ...\nnova-cert start/running, process 10754\nSetting up vlan (1.9-3ubuntu6) ...\nSetting up nova-consoleauth (2012.1-0ubuntu2.3) ...\nnova-consoleauth start/running, process 10800\nSetting up nova-doc (2012.1-0ubuntu2.3) ...\nSetting up nova-network (2012.1-0ubuntu2.3) ...\nnova-network start/running, process 10847\nSetting up nova-scheduler (2012.1-0ubuntu2.3) ...\nnova-scheduler start/running, process 10896\nSetting up nova-vncproxy (2012.1-0ubuntu2.3) ...\nnova-vncproxy start/running, process 10937\nSetting up nova-volume (2012.1-0ubuntu2.3) ...\nnova-volume start/running, process 10986\nSetting up nova-compute-kvm (2012.1-0ubuntu2.3) ...\nSetting up nova-compute (2012.1-0ubuntu2.3) ...\nAdding user `nova' to group `libvirtd' ...\nAdding user nova to group libvirtd\nDone.\nnova-compute start/running, process 11073\nProcessing triggers for libc-bin ...\nldconfig deferred processing now taking place\nProcessing triggers for initramfs-tools ...\nupdate-initramfs: Generating /boot/initrd.img-3.2.0-24-virtual\n============================================================================\n", 
            "date_created": "2012-06-15 13:14:04.984395+00:00", 
            "author": "https://api.launchpad.net/1.0/~panpengjun"
        }, 
        {
            "content": "As Vish says, that DEBUG line is is not indicative of an error. There is no failure: the command actually works successfully. Please reopen (set back to New) if you disagree, and can point to an error in the logs.", 
            "date_created": "2012-07-12 13:28:38.177582+00:00", 
            "author": "https://api.launchpad.net/1.0/~ttx"
        }
    ], 
    "closed": "2012-07-12 13:28:40.458505+00:00"
}