{
    "status": "Fix Released", 
    "last_updated": "2013-10-17 11:42:22.729558+00:00", 
    "description": "Exception handler calls forget_sr which blocks and clears the exception-context before trying to re-raise the exception.\n\nSince the exception context has been cleared, we get an error on reraise that looks like:\n\n\n\nexceptions must be old-style classes or derived from BaseException, not NoneType", 
    "tags": [
        "xenserver"
    ], 
    "importance": "Medium", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1167515", 
    "owner": "https://api.launchpad.net/1.0/~rconradharris", 
    "id": 1167515, 
    "index": 3349, 
    "openned": "2013-04-10 19:00:10.910238+00:00", 
    "created": "2013-04-10 19:00:10.910238+00:00", 
    "title": "xenapi: _connect_volume exception handler not eventlet safe", 
    "comments": [
        {
            "content": "Exception handler calls forget_sr which blocks and clears the exception-context before trying to re-raise the exception.\n\nSince the exception context has been cleared, we get an error on reraise that looks like:\n\n\n\nexceptions must be old-style classes or derived from BaseException, not NoneType", 
            "date_created": "2013-04-10 19:00:10.910238+00:00", 
            "author": "https://api.launchpad.net/1.0/~rconradharris"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/26657", 
            "date_created": "2013-04-10 19:06:26.698789+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/26657\nCommitted: http://github.com/openstack/nova/commit/a2a9f16889b5b74de0daccab3e5011ad0f4d1e94\nSubmitter: Jenkins\nBranch:    master\n\ncommit a2a9f16889b5b74de0daccab3e5011ad0f4d1e94\nAuthor: Rick Harris <email address hidden>\nDate:   Wed Apr 10 19:04:30 2013 +0000\n\n    xenapi: Make _connect_volume exc handler eventlet safe\n    \n    `forget_sr` blocks and so clears the exception state causing the\n    subsequent raise to try to raise `None`, which fails.\n    \n    Fixes bug 1167515\n    \n    Change-Id: I18562c7389b152a6490d352c5a8d36934288f47d\n", 
            "date_created": "2013-04-16 18:23:28.816875+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ], 
    "closed": "2013-05-29 10:25:57.981906+00:00"
}