{
    "status": "Fix Released", 
    "last_updated": "2015-11-19 21:48:14.720150+00:00", 
    "description": "When trusted filter in nova scheduler is running with default value of attestation_port:\n\ncfg.StrOpt('attestation_port', default='8443', help='Attestation server port'),\n\nmethod _do_request() in AttestationService class has this line:\n\naction_url = \"https://%s:%d%s/%s\" % (self.host, self.port, self.api_url, action_url)\n\nIt is easy to see that default type of attestation_port is string. \nBut in action_url self.port is required as integer (%d). It leads to conflict.", 
    "tags": [
        "in-stable-icehouse", 
        "in-stable-juno", 
        "low-hanging-fruit", 
        "nova"
    ], 
    "importance": "High", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1381468", 
    "owner": "https://api.launchpad.net/1.0/~bartosz-fic", 
    "id": 1381468, 
    "index": 1639, 
    "openned": "2014-10-15 11:19:47.741506+00:00", 
    "created": "2014-10-15 11:19:47.741506+00:00", 
    "title": "Type conflict in nova/nova/scheduler/filters/trusted_filter.py using attestation_port default value", 
    "comments": [
        {
            "content": "When trusted filter in nova scheduler is running with default value of attestation_port:\n\ncfg.StrOpt('attestation_port', default='8443', help='Attestation server port'),\n\nmethod _do_request() in AttestationService class has this line:\n\naction_url = \"https://%s:%d%s/%s\" % (self.host, self.port, self.api_url, action_url)\n\nIt is easy to see that default type of attestation_port is string. \nBut in action_url self.port is required as integer (%d). It leads to conflict.", 
            "date_created": "2014-10-15 11:19:47.741506+00:00", 
            "author": "https://api.launchpad.net/1.0/~bartosz-fic"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/128624", 
            "date_created": "2014-10-15 12:07:59.816482+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "I've commited few tests.", 
            "date_created": "2014-11-05 10:00:08.590307+00:00", 
            "author": "https://api.launchpad.net/1.0/~bartosz-fic"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/128624\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=fdcf358eaeef6edb5c8d2dcc94f906a22882544a\nSubmitter: Jenkins\nBranch:    master\n\ncommit fdcf358eaeef6edb5c8d2dcc94f906a22882544a\nAuthor: Bartosz Fic <email address hidden>\nDate:   Mon Nov 17 12:04:59 2014 +0100\n\n    Type conflict in trusted_filter.py using attestation_port default value\n    \n    When trusted filter (nova/nova/scheduler/filters/trusted_filter.py)\n    in nova scheduler is running with default value of attestation_port:\n    \n    default='8443'\n    \n    method _do_request() in AttestationService class has this line:\n    \n    action_url = \"https://%s:%d%s/%s\" % (self.host,\n    self.port, self.api_url, action_url)\n    \n    It is easy to see that default type of attestation_port is string.\n    But in action_url self.port is required as integer (%d).\n    It leads to conflict.\n    \n    This change provides more tests than is required only to cover this bug\n    fix. This cases are testing AttestationService _do_request() method\n    using different status_codes and different texts returned by mocked\n    request method.\n    \n    Change-Id: I1ad57b5bd1986360416948fd00dec22456dc29a7\n    Closes-Bug: #1381468\n", 
            "date_created": "2014-12-01 20:29:17.587307+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: stable/juno\nReview: https://review.openstack.org/176797", 
            "date_created": "2015-04-23 15:03:16.600144+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Fix proposed to branch: stable/icehouse\nReview: https://review.openstack.org/176873", 
            "date_created": "2015-04-23 15:55:06.720360+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/176797\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=b251958e61a62aea7facea574e7aca366af4b004\nSubmitter: Jenkins\nBranch:    stable/juno\n\ncommit b251958e61a62aea7facea574e7aca366af4b004\nAuthor: Bartosz Fic <email address hidden>\nDate:   Mon Nov 17 12:04:59 2014 +0100\n\n    Type conflict in trusted_filter.py using attestation_port default value\n    \n    When trusted filter (nova/nova/scheduler/filters/trusted_filter.py)\n    in nova scheduler is running with default value of attestation_port:\n    \n    default='8443'\n    \n    method _do_request() in AttestationService class has this line:\n    \n    action_url = \"https://%s:%d%s/%s\" % (self.host,\n    self.port, self.api_url, action_url)\n    \n    It is easy to see that default type of attestation_port is string.\n    But in action_url self.port is required as integer (%d).\n    It leads to conflict.\n    \n    This change provides more tests than is required only to cover this bug\n    fix. This cases are testing AttestationService _do_request() method\n    using different status_codes and different texts returned by mocked\n    request method.\n    \n    (cherry picked from commit fdcf358eaeef6edb5c8d2dcc94f906a22882544a)\n    \n    Conflicts:\n    \tnova/tests/unit/scheduler/filters/test_trusted_filters.py\n    \n    Tests aren't in tests/unit/.\n    \n    Use jsonutils from nova.openstack.common instead of oslo.utils.\n    \n    Closes-Bug: #1381468\n    Change-Id: I1ad57b5bd1986360416948fd00dec22456dc29a7\n", 
            "date_created": "2015-05-03 15:44:02.145265+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/176873\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=b77c188ad686970184edd0821986a912c2643dc5\nSubmitter: Jenkins\nBranch:    stable/icehouse\n\ncommit b77c188ad686970184edd0821986a912c2643dc5\nAuthor: Bartosz Fic <email address hidden>\nDate:   Mon Nov 17 12:04:59 2014 +0100\n\n    Type conflict in trusted_filter.py using attestation_port default value\n    \n    When trusted filter (nova/nova/scheduler/filters/trusted_filter.py)\n    in nova scheduler is running with default value of attestation_port:\n    \n    default='8443'\n    \n    method _do_request() in AttestationService class has this line:\n    \n    action_url = \"https://%s:%d%s/%s\" % (self.host,\n    self.port, self.api_url, action_url)\n    \n    It is easy to see that default type of attestation_port is string.\n    But in action_url self.port is required as integer (%d).\n    It leads to conflict.\n    \n    This change provides more tests than is required only to cover this bug\n    fix. This cases are testing AttestationService _do_request() method\n    using different status_codes and different texts returned by mocked\n    request method.\n    \n    (cherry picked from commit fdcf358eaeef6edb5c8d2dcc94f906a22882544a)\n    \n    Conflicts:\n    \tnova/tests/unit/scheduler/filters/test_trusted_filters.py\n    \n    Tests aren't in tests/unit/.\n    \n    Use jsonutils from nova.openstack.common instead of oslo.utils.\n    \n    (cherry picked from commit b251958e61a62aea7facea574e7aca366af4b004)\n    \n    Closes-Bug: #1381468\n    Change-Id: I1ad57b5bd1986360416948fd00dec22456dc29a7\n", 
            "date_created": "2015-05-28 20:31:40.397816+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ], 
    "closed": "2014-12-18 20:04:11.404379+00:00"
}