{
    "status": "Fix Released", 
    "last_updated": "2015-04-30 09:19:20.468442+00:00", 
    "description": "To reproduce the problem:\n\nRemove ServerGroupAntiAffinity from scheduler_default_filters in nova.conf\n\n$ nova server-group-create my-anti-affinity anti-affinity\n$ nova boot --flavor 42 --image 1b0ef685-2a7a-4c11-8e2d-a549215c1b3a --hint group=<uuid of the group created above> vm23\n\nThe following exception is visible in the conductor log:\n2015-01-07 15:33:44.988 ERROR nova.scheduler.utils [req-675e5f28-59c4-4406-952c-182202aae805 admin admin] ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 ERROR oslo.messaging.rpc.dispatcher [req-675e5f28-59c4-4406-952c-182202aae805 admin admin] Exception during message handling: No valid host was found. ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher Traceback (most recent call last):\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 137, in _dispatch_and_reply\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     incoming.message))\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 180, in _dispatch\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 126, in _do_dispatch\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     result = getattr(endpoint, method)(ctxt, **new_args)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/conductor/manager.py\", line 626, in build_instances\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     filter_properties)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/scheduler/utils.py\", line 311, in setup_instance_group\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     group_info = _get_group_details(context, instance_uuid, group_hosts)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/scheduler/utils.py\", line 291, in _get_group_details\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     raise exception.NoValidHost(reason=msg)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher NoValidHost: No valid host was found. ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher \n\nBut the server stuck in scheduling state for ever. \n$ nova list\n+--------------------------------------+------+--------+------------+-------------+--------------------+\n| ID                                   | Name | Status | Task State | Power State | Networks           |\n+--------------------------------------+------+--------+------------+-------------+--------------------+\n| 4b919b5c-1db4-4705-a608-8ce8db862b07 | vm23 | BUILD  | scheduling | NOSTATE     |                    |\n+--------------------------------------+------+--------+------------+-------------+--------------------+", 
    "tags": [
        "scheduler"
    ], 
    "importance": "Low", 
    "heat": 8, 
    "link": "https://bugs.launchpad.net/nova/+bug/1408326", 
    "owner": "https://api.launchpad.net/1.0/~ildiko-vancsa", 
    "id": 1408326, 
    "index": 1479, 
    "openned": "2015-01-07 14:51:52.106194+00:00", 
    "created": "2015-01-07 14:51:52.106194+00:00", 
    "title": "Server booted to a server group stucks in scheduling state if the policy filter is not configured", 
    "comments": [
        {
            "content": "To reproduce the problem:\n\nRemove ServerGroupAntiAffinity from scheduler_default_filters in nova.conf\n\n$ nova server-group-create my-anti-affinity anti-affinity\n$ nova boot --flavor 42 --image 1b0ef685-2a7a-4c11-8e2d-a549215c1b3a --hint group=<uuid of the group created above> vm23\n\nThe following exception is visible in the conductor log:\n2015-01-07 15:33:44.988 ERROR nova.scheduler.utils [req-675e5f28-59c4-4406-952c-182202aae805 admin admin] ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 ERROR oslo.messaging.rpc.dispatcher [req-675e5f28-59c4-4406-952c-182202aae805 admin admin] Exception during message handling: No valid host was found. ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher Traceback (most recent call last):\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 137, in _dispatch_and_reply\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     incoming.message))\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 180, in _dispatch\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     return self._do_dispatch(endpoint, method, ctxt, args)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/usr/local/lib/python2.7/dist-packages/oslo/messaging/rpc/dispatcher.py\", line 126, in _do_dispatch\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     result = getattr(endpoint, method)(ctxt, **new_args)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/conductor/manager.py\", line 626, in build_instances\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     filter_properties)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/scheduler/utils.py\", line 311, in setup_instance_group\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     group_info = _get_group_details(context, instance_uuid, group_hosts)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher   File \"/opt/stack/nova/nova/scheduler/utils.py\", line 291, in _get_group_details\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher     raise exception.NoValidHost(reason=msg)\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher NoValidHost: No valid host was found. ServerGroupAntiAffinityFilter not configured\n2015-01-07 15:33:44.988 TRACE oslo.messaging.rpc.dispatcher \n\nBut the server stuck in scheduling state for ever. \n$ nova list\n+--------------------------------------+------+--------+------------+-------------+--------------------+\n| ID                                   | Name | Status | Task State | Power State | Networks           |\n+--------------------------------------+------+--------+------------+-------------+--------------------+\n| 4b919b5c-1db4-4705-a608-8ce8db862b07 | vm23 | BUILD  | scheduling | NOSTATE     |                    |\n+--------------------------------------+------+--------+------------+-------------+--------------------+", 
            "date_created": "2015-01-07 14:51:52.106194+00:00", 
            "author": "https://api.launchpad.net/1.0/~balazs-gibizer"
        }, 
        {
            "content": "Can you share your nova.conf (at least the part relative to Filter Scheduler)?", 
            "date_created": "2015-01-07 16:47:03.172476+00:00", 
            "author": "https://api.launchpad.net/1.0/~pasquale-porreca"
        }, 
        {
            "content": "The only thing I changed from the default devstack nova.conf is that I removed the ServerGroupAntiAffinityFilter form the scheduler_default_filters to trigger the code path that rejects the scheduling of a server to a group with anti-affinity policy as the \nfilter is not available. \n\nSo basically I added the following line to the default devstack nova.conf:\nscheduler_default_filters = RetryFilter, AvailabilityZoneFilter, RamFilter, ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAffinityFilter\n\n\nI checked the conductor code and the not handled exception is coming from here https://github.com/openstack/nova/blob/master/nova/conductor/manager.py#L625 and the solution is straightforward. Basically we have to move the scheduler_utils.setup_instance_group() call to the try - except block below. \n\nI'm working on a patch that will fi the problem.", 
            "date_created": "2015-01-08 08:36:59.485969+00:00", 
            "author": "https://api.launchpad.net/1.0/~balazs-gibizer"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/145761", 
            "date_created": "2015-01-08 12:20:31.328075+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Is this bug also present in Juno? If so, can you add the appropiate juno-backport-potential? Thanks.", 
            "date_created": "2015-01-08 15:10:03.188451+00:00", 
            "author": "https://api.launchpad.net/1.0/~cbelu"
        }, 
        {
            "content": "I will test it on Juno to see if it needs to be backported.", 
            "date_created": "2015-01-08 15:19:33.259489+00:00", 
            "author": "https://api.launchpad.net/1.0/~balazs-gibizer"
        }, 
        {
            "content": "This bug is not present in Juno (or Icehouse) as the problem is introduced in this change https://review.openstack.org/#/c/128058/ and that change merged in Kilo-1 only. Therefore no backporting effort is needed.", 
            "date_created": "2015-01-09 13:09:43.198414+00:00", 
            "author": "https://api.launchpad.net/1.0/~balazs-gibizer"
        }, 
        {
            "content": "IMO, the bug is that setup_instance_group() is raising NoValidHost when the anti-affinity filter is not enabled. The exception raised should be more descriptive of the problem... for example something like FilterConfigurationError or UnsupportedPolicyException.", 
            "date_created": "2015-01-25 18:27:00.425615+00:00", 
            "author": "https://api.launchpad.net/1.0/~jaypipes"
        }, 
        {
            "content": "Setting to Low because this is partly a configuration issue, and not something that is common to run into.", 
            "date_created": "2015-01-25 18:27:53.299970+00:00", 
            "author": "https://api.launchpad.net/1.0/~jaypipes"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/145761\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=28aedc604d993be4b1b38822fd08500df94b6ce3\nSubmitter: Jenkins\nBranch:    master\n\ncommit 28aedc604d993be4b1b38822fd08500df94b6ce3\nAuthor: Balazs Gibizer <email address hidden>\nDate:   Wed Jan 7 16:01:38 2015 +0100\n\n    Fix leaking exceptions from scheduler utils\n    \n    scheduler_utils.setup_instance_group() can raise NoValidHost\n    exception and the conductor does not handle that properly which\n    causes the server to get stuck in a scheduling state instead of\n    going to ERROR.\n    \n    The function is called several times in conductor/manager.py. This\n    patch moves the function calls in the try blocks already present.\n    It handles the missing Affinity filters as UnsupportedPolicyException,\n    which is a new exception type added here. This way the exception\n    raised by scheduler_utils.setup_instance_group() will cause the\n    VM to end up in ERROR state instead of NOSTATE, as it is expected.\n    Quota rollback is also handled properly, when it is needed.\n    \n    Closes-bug: #1408326\n    Change-Id: I3a8ba37ded8ac3fa9b5f3f35b09feb82d822d583\n", 
            "date_created": "2015-02-02 18:18:38.205440+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ], 
    "closed": "2015-02-05 20:22:05.982756+00:00"
}