{
    "status": "Fix Released", 
    "last_updated": "2015-10-15 09:01:52.653760+00:00", 
    "description": "In the event that an instance is deleted during the driver get_info method then the instance may not be correctly set. This is due to the fact that the VMware driver does not raise the correct exception.", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1464979", 
    "owner": "https://api.launchpad.net/1.0/~garyk", 
    "id": 1464979, 
    "index": 6872, 
    "openned": "2015-06-14 09:24:30.112389+00:00", 
    "created": "2015-06-14 09:24:30.112389+00:00", 
    "title": "VMware: _get_power_state does not set correct power state", 
    "comments": [
        {
            "content": "In the event that an instance is deleted during the driver get_info method then the instance may not be correctly set. This is due to the fact that the VMware driver does not raise the correct exception.", 
            "date_created": "2015-06-14 09:24:30.112389+00:00", 
            "author": "https://api.launchpad.net/1.0/~garyk"
        }, 
        {
            "content": "Fix proposed to branch: master\nReview: https://review.openstack.org/191558", 
            "date_created": "2015-06-14 09:28:44.250274+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }, 
        {
            "content": "Reviewed:  https://review.openstack.org/191558\nCommitted: https://git.openstack.org/cgit/openstack/nova/commit/?id=ca6a563715428bfe56e85e1a67e77da99de2939a\nSubmitter: Jenkins\nBranch:    master\n\ncommit ca6a563715428bfe56e85e1a67e77da99de2939a\nAuthor: Gary Kotton <email address hidden>\nDate:   Sun Jun 14 02:21:37 2015 -0700\n\n    VMware: ensure that get_info raises the correct exception\n    \n    In the event that a instance is deleted during the get_info method\n    then the method would not raise the correct exception.\n    \n    If the instance no longer exists then the VC will raise\n    a 'ManagedObjectNotFound' exception.\n    \n    Note that the oslo.vmware patch that supports this exception is:\n    https://review.openstack.org/#/c/191553/\n    \n    This exception handling is treated by using vexc.register_fault_class\n    to support the local exception (until replaced by oslo.vmware)\n    \n    Co-Authored-By: Radoslav Gerganov <email address hidden>\n    \n    Change-Id: I2d4b131789319cfd1322cbc95edd7822114532e1\n    Closes-bug: #1464979\n", 
            "date_created": "2015-08-17 23:57:26.139651+00:00", 
            "author": "https://api.launchpad.net/1.0/~hudson-openstack"
        }
    ], 
    "closed": "2015-09-03 11:51:04.767418+00:00"
}