{
    "status": "Invalid", 
    "last_updated": "2015-12-13 20:10:08.710333+00:00", 
    "description": "Seen here:\n\nhttp://logs.openstack.org/11/246211/19/check/gate-grenade-dsvm/06a815e/logs/new/screen-n-api.txt.gz?level=TRACE\n\n2015-12-09 07:52:44.729 3354 ERROR nova Traceback (most recent call last):\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/bin/nova-api\", line 10, in <module>\n2015-12-09 07:52:44.729 3354 ERROR nova     sys.exit(main())\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/cmd/api.py\", line 55, in main\n2015-12-09 07:52:44.729 3354 ERROR nova     server = service.WSGIService(api, use_ssl=should_use_ssl)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/service.py\", line 328, in __init__\n2015-12-09 07:52:44.729 3354 ERROR nova     self.app = self.loader.load_app(name)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/wsgi.py\", line 543, in load_app\n2015-12-09 07:52:44.729 3354 ERROR nova     return deploy.loadapp(\"config:%s\" % self.config_path, name=name)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 247, in loadapp\n2015-12-09 07:52:44.729 3354 ERROR nova     return loadobj(APP, uri, name=name, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 272, in loadobj\n2015-12-09 07:52:44.729 3354 ERROR nova     return context.create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 710, in create\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.object_type.invoke(self)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 144, in invoke\n2015-12-09 07:52:44.729 3354 ERROR nova     **context.local_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py\", line 55, in fix_call\n2015-12-09 07:52:44.729 3354 ERROR nova     val = callable(*args, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/openstack/urlmap.py\", line 160, in urlmap_factory\n2015-12-09 07:52:44.729 3354 ERROR nova     app = loader.get_app(app_name, global_conf=global_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 350, in get_app\n2015-12-09 07:52:44.729 3354 ERROR nova     name=name, global_conf=global_conf).create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 710, in create\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.object_type.invoke(self)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 144, in invoke\n2015-12-09 07:52:44.729 3354 ERROR nova     **context.local_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py\", line 55, in fix_call\n2015-12-09 07:52:44.729 3354 ERROR nova     val = callable(*args, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/auth.py\", line 73, in pipeline_factory\n2015-12-09 07:52:44.729 3354 ERROR nova     return _load_pipeline(loader, pipeline)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/auth.py\", line 57, in _load_pipeline\n2015-12-09 07:52:44.729 3354 ERROR nova     filters = [loader.get_filter(n) for n in pipeline[:-1]]\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 354, in get_filter\n2015-12-09 07:52:44.729 3354 ERROR nova     name=name, global_conf=global_conf).create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 366, in filter_context\n2015-12-09 07:52:44.729 3354 ERROR nova     FILTER, name=name, global_conf=global_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 458, in get_context\n2015-12-09 07:52:44.729 3354 ERROR nova     section)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 517, in _context_from_explicit\n2015-12-09 07:52:44.729 3354 ERROR nova     value = import_string(found_expr)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 22, in import_string\n2015-12-09 07:52:44.729 3354 ERROR nova     return pkg_resources.EntryPoint.parse(\"x=\" + s).load(False)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2380, in load\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.resolve()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2386, in resolve\n2015-12-09 07:52:44.729 3354 ERROR nova     module = __import__(self.module_name, fromlist=['__name__'], level=0)\n2015-12-09 07:52:44.729 3354 ERROR nova ImportError: No module named middleware\n2015-12-09 07:52:44.729 3354 ERROR nova \n\nProposal to cap oslo.middleware at <3 here: https://review.openstack.org/#/c/255245/", 
    "tags": [
        "api", 
        "oslo", 
        "upgrade"
    ], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1524404", 
    "owner": "None", 
    "id": 1524404, 
    "index": 7164, 
    "openned": "2015-12-09 16:14:34.118469+00:00", 
    "created": "2015-12-09 16:14:34.118469+00:00", 
    "title": "grenade jobs on stable/liberty broken with oslo.middleware>=3", 
    "comments": [
        {
            "content": "Seen here:\n\nhttp://logs.openstack.org/11/246211/19/check/gate-grenade-dsvm/06a815e/logs/new/screen-n-api.txt.gz?level=TRACE\n\n2015-12-09 07:52:44.729 3354 ERROR nova Traceback (most recent call last):\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/bin/nova-api\", line 10, in <module>\n2015-12-09 07:52:44.729 3354 ERROR nova     sys.exit(main())\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/cmd/api.py\", line 55, in main\n2015-12-09 07:52:44.729 3354 ERROR nova     server = service.WSGIService(api, use_ssl=should_use_ssl)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/service.py\", line 328, in __init__\n2015-12-09 07:52:44.729 3354 ERROR nova     self.app = self.loader.load_app(name)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/wsgi.py\", line 543, in load_app\n2015-12-09 07:52:44.729 3354 ERROR nova     return deploy.loadapp(\"config:%s\" % self.config_path, name=name)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 247, in loadapp\n2015-12-09 07:52:44.729 3354 ERROR nova     return loadobj(APP, uri, name=name, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 272, in loadobj\n2015-12-09 07:52:44.729 3354 ERROR nova     return context.create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 710, in create\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.object_type.invoke(self)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 144, in invoke\n2015-12-09 07:52:44.729 3354 ERROR nova     **context.local_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py\", line 55, in fix_call\n2015-12-09 07:52:44.729 3354 ERROR nova     val = callable(*args, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/openstack/urlmap.py\", line 160, in urlmap_factory\n2015-12-09 07:52:44.729 3354 ERROR nova     app = loader.get_app(app_name, global_conf=global_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 350, in get_app\n2015-12-09 07:52:44.729 3354 ERROR nova     name=name, global_conf=global_conf).create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 710, in create\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.object_type.invoke(self)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 144, in invoke\n2015-12-09 07:52:44.729 3354 ERROR nova     **context.local_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/util.py\", line 55, in fix_call\n2015-12-09 07:52:44.729 3354 ERROR nova     val = callable(*args, **kw)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/auth.py\", line 73, in pipeline_factory\n2015-12-09 07:52:44.729 3354 ERROR nova     return _load_pipeline(loader, pipeline)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/opt/stack/new/nova/nova/api/auth.py\", line 57, in _load_pipeline\n2015-12-09 07:52:44.729 3354 ERROR nova     filters = [loader.get_filter(n) for n in pipeline[:-1]]\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 354, in get_filter\n2015-12-09 07:52:44.729 3354 ERROR nova     name=name, global_conf=global_conf).create()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 366, in filter_context\n2015-12-09 07:52:44.729 3354 ERROR nova     FILTER, name=name, global_conf=global_conf)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 458, in get_context\n2015-12-09 07:52:44.729 3354 ERROR nova     section)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 517, in _context_from_explicit\n2015-12-09 07:52:44.729 3354 ERROR nova     value = import_string(found_expr)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/paste/deploy/loadwsgi.py\", line 22, in import_string\n2015-12-09 07:52:44.729 3354 ERROR nova     return pkg_resources.EntryPoint.parse(\"x=\" + s).load(False)\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2380, in load\n2015-12-09 07:52:44.729 3354 ERROR nova     return self.resolve()\n2015-12-09 07:52:44.729 3354 ERROR nova   File \"/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py\", line 2386, in resolve\n2015-12-09 07:52:44.729 3354 ERROR nova     module = __import__(self.module_name, fromlist=['__name__'], level=0)\n2015-12-09 07:52:44.729 3354 ERROR nova ImportError: No module named middleware\n2015-12-09 07:52:44.729 3354 ERROR nova \n\nProposal to cap oslo.middleware at <3 here: https://review.openstack.org/#/c/255245/", 
            "date_created": "2015-12-09 16:14:34.118469+00:00", 
            "author": "https://api.launchpad.net/1.0/~mriedem"
        }, 
        {
            "content": "http://logstash.openstack.org/#dashboard/file/logstash.json?query=message:%5C%22ImportError:%20No%20module%20named%20middleware%5C%22%20AND%20tags:%5C%22screen-n-api.txt%5C%22", 
            "date_created": "2015-12-09 16:58:28.539073+00:00", 
            "author": "https://api.launchpad.net/1.0/~mriedem"
        }, 
        {
            "content": "Actually this is the right thing happening.  The change that's failing is the upper-constraints change for stable/liberty:\n\nhttps://review.openstack.org/#/c/246211/\n\nSo if we just never fix that, upper-constraints on stable/liberty is frozen, which is maybe acceptable.", 
            "date_created": "2015-12-09 18:29:10.713214+00:00", 
            "author": "https://api.launchpad.net/1.0/~mriedem"
        }, 
        {
            "content": "This issue was fixed in the openstack/oslo.middleware 3.2.0 release.", 
            "date_created": "2015-12-11 15:19:48.788390+00:00", 
            "author": "https://api.launchpad.net/1.0/~dims-v"
        }, 
        {
            "content": "Should be fixed with \"oslo.middleware===3.3.0\" in stable/liberty g-r\n\nPlease see https://jenkins04.openstack.org/job/gate-grenade-dsvm/9750/console\n\nthat jenkins job was run using\n\nhttps://review.openstack.org/#/c/246211/25/upper-constraints.txt,cm\n\nThanks,\nDims", 
            "date_created": "2015-12-13 20:09:55.233525+00:00", 
            "author": "https://api.launchpad.net/1.0/~dims-v"
        }
    ], 
    "closed": "2015-12-09 16:14:47.845423+00:00"
}