{
    "status": "Fix Released", 
    "last_updated": "2014-04-17 08:58:25.040620+00:00", 
    "description": "http://logs.openstack.org/82/25882/10/check/check-tempest-dsvm-full/01bb021/logs/screen-n-api.txt.gz?level=TRACE#_2013-12-20_06_40_39_590\n\n2013-12-20 06:40:39.590 ERROR nova.api.openstack Caught error: Timeout while waiting on RPC response - topic: \"compute.devstack-precise-hpcloud-az2-902809\", RPC method: \"get_console_output\" info: \"<unknown>\"\n<...>\n2013-12-20 06:40:39.590 25870 TRACE nova.api.openstack Timeout: Timeout while waiting on RPC response - topic: \"compute.devstack-precise-hpcloud-az2-902809\", RPC method: \"get_console_output\" info: \"<unknown>\"\n\nBecause of this, the gate job of check-tempest-dsvm-full has been failed.\n\nlogstash query: message:\"nova.api.openstack Timeout: Timeout while waiting on RPC response - topic: \\\"\" AND message:\", RPC method: \\\"get_console_output\\\"\"", 
    "tags": [], 
    "importance": "High", 
    "heat": 14, 
    "link": "https://bugs.launchpad.net/nova/+bug/1263032", 
    "owner": "None", 
    "id": 1263032, 
    "index": 1355, 
    "openned": "2013-12-20 09:05:52.291376+00:00", 
    "created": "2013-12-20 09:05:52.291376+00:00", 
    "title": "Timeout while waiting on RPC response - topic: 'compute.devstack-*', RPC method: 'get_console_output' info: '<unknown>'", 
    "comments": [
        {
            "content": "http://logs.openstack.org/82/25882/10/check/check-tempest-dsvm-full/01bb021/logs/screen-n-api.txt.gz?level=TRACE#_2013-12-20_06_40_39_590\n\n2013-12-20 06:40:39.590 ERROR nova.api.openstack Caught error: Timeout while waiting on RPC response - topic: \"compute.devstack-precise-hpcloud-az2-902809\", RPC method: \"get_console_output\" info: \"<unknown>\"\n<...>\n2013-12-20 06:40:39.590 25870 TRACE nova.api.openstack Timeout: Timeout while waiting on RPC response - topic: \"compute.devstack-precise-hpcloud-az2-902809\", RPC method: \"get_console_output\" info: \"<unknown>\"\n\nBecause of this, the gate job of check-tempest-dsvm-full has been failed.\n\nlogstash query: message:\"nova.api.openstack Timeout: Timeout while waiting on RPC response - topic: \\\"\" AND message:\", RPC method: \\\"get_console_output\\\"", 
            "date_created": "2013-12-20 09:05:52.291376+00:00", 
            "author": "https://api.launchpad.net/1.0/~igawa"
        }, 
        {
            "content": "may be this is the same bug when get messages like:  \n    \nError: Failed to launch instance \"hddd\": Please try again later [Error: Timeout while waiting on RPC response - topic: \"network.eccp-compute1.local.com\", RPC method: \"deallocate_for_instance\" info: \"<unknown>\"].", 
            "date_created": "2014-01-14 08:44:56.907635+00:00", 
            "author": "https://api.launchpad.net/1.0/~gzsgwsgwl"
        }, 
        {
            "content": "this error occur when controller resource is not enough to request compute node, and at the same time it is ok when all vms launched in controller.", 
            "date_created": "2014-01-14 09:05:44.903546+00:00", 
            "author": "https://api.launchpad.net/1.0/~gzsgwsgwl"
        }, 
        {
            "content": "sorry,my fault. the above problem is not the same bug,it is only my wrong config.", 
            "date_created": "2014-01-14 09:30:38.735151+00:00", 
            "author": "https://api.launchpad.net/1.0/~gzsgwsgwl"
        }, 
        {
            "content": "This hasn't been seen in two weeks in logstash, marking as fixed", 
            "date_created": "2014-01-20 02:49:35.186742+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }
    ], 
    "closed": "2014-01-22 16:14:01.753260+00:00"
}