{
    "status": "Fix Released", 
    "last_updated": "2011-09-22 12:55:55.453585+00:00", 
    "description": "2011-09-19 18:56:26,981 CRITICAL nova [-] create() got an unexpected keyword argument 'net_uuid'\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"bin/nova-manage\", line 2097, in <module>\n(nova): TRACE:     main()\n(nova): TRACE:   File \"bin/nova-manage\", line 2085, in main\n(nova): TRACE:     fn(*fn_args, **fn_kwargs)\n(nova): TRACE: TypeError: create() got an unexpected keyword argument 'net_uuid'\n(nova): TRACE:", 
    "tags": [], 
    "importance": "Medium", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/854322", 
    "owner": "https://api.launchpad.net/1.0/~bmcconne", 
    "id": 854322, 
    "index": 2568, 
    "created": "2011-09-19 23:57:56.767147+00:00", 
    "title": "nova-manage fails when creating networks associated with a quantum id", 
    "comments": [
        {
            "content": "2011-09-19 18:56:26,981 CRITICAL nova [-] create() got an unexpected keyword argument 'net_uuid'\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"bin/nova-manage\", line 2097, in <module>\n(nova): TRACE:     main()\n(nova): TRACE:   File \"bin/nova-manage\", line 2085, in main\n(nova): TRACE:     fn(*fn_args, **fn_kwargs)\n(nova): TRACE: TypeError: create() got an unexpected keyword argument 'net_uuid'\n(nova): TRACE:", 
            "date_created": "2011-09-19 23:57:56.767147+00:00", 
            "author": "https://api.launchpad.net/1.0/~bmcconne"
        }
    ]
}