{
    "status": "Invalid", 
    "last_updated": "2015-01-21 04:17:24.701559+00:00", 
    "description": "Gate jobs failed on 'gate-tempest-dsvm-neutron-full' with following error.\n\nClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-7d7ab999-1351-43be-bd51-96a100a7cdeb)\n\nDetailed stack trace is:\n\nRESP BODY: {\"itemNotFound\": {\"message\": \"Instance could not be found\", \"code\": 404}}\n}}}\n\nTraceback (most recent call last):\nFile \"tempest/scenario/test_network_advanced_server_ops.py\", line 73, in setUp\ncreate_kwargs=create_kwargs)\nFile \"tempest/scenario/manager.py\", line 778, in create_server\nself.status_timeout(client.servers, server.id, 'ACTIVE')\nFile \"tempest/scenario/manager.py\", line 572, in status_timeout\nnot_found_exception=not_found_exception)\nFile \"tempest/scenario/manager.py\", line 635, in _status_timeout\nCONF.compute.build_interval):\nFile \"tempest/test.py\", line 614, in call_until_true\nif func():\nFile \"tempest/scenario/manager.py\", line 606, in check_status\nthing = things.get(thing_id)\nFile \"/opt/stack/new/python-novaclient/novaclient/v1_1/servers.py\", line 555, in get\nreturn self._get(\"/servers/%s\" % base.getid(server), \"server\")\nFile \"/opt/stack/new/python-novaclient/novaclient/base.py\", line 93, in _get\n_resp, body = self.api.client.get(url)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 487, in get\nreturn self._cs_request(url, 'GET', **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 465, in _cs_request\nresp, body = self._time_request(url, method, **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 439, in _time_request\nresp, body = self.request(url, method, **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 433, in request\nraise exceptions.from_response(resp, body, url, method)\n ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-7d7ab999-1351-43be-bd51-96a100a7cdeb)\n\nTraceback (most recent call last):\nStringException: Empty attachments:\nstderr\nstdout", 
    "tags": [
        "testing"
    ], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/1363103", 
    "owner": "None", 
    "id": 1363103, 
    "index": 5126, 
    "created": "2014-08-29 14:05:28.336445+00:00", 
    "title": "OperationalError: (OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') 'INSERT INTO routerl3agentbindings", 
    "comments": [
        {
            "content": "Gate jobs failed on 'gate-tempest-dsvm-neutron-full' with following error.\n\nClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-7d7ab999-1351-43be-bd51-96a100a7cdeb)\n\nDetailed stack trace is:\n\nRESP BODY: {\"itemNotFound\": {\"message\": \"Instance could not be found\", \"code\": 404}}\n}}}\n\nTraceback (most recent call last):\nFile \"tempest/scenario/test_network_advanced_server_ops.py\", line 73, in setUp\ncreate_kwargs=create_kwargs)\nFile \"tempest/scenario/manager.py\", line 778, in create_server\nself.status_timeout(client.servers, server.id, 'ACTIVE')\nFile \"tempest/scenario/manager.py\", line 572, in status_timeout\nnot_found_exception=not_found_exception)\nFile \"tempest/scenario/manager.py\", line 635, in _status_timeout\nCONF.compute.build_interval):\nFile \"tempest/test.py\", line 614, in call_until_true\nif func():\nFile \"tempest/scenario/manager.py\", line 606, in check_status\nthing = things.get(thing_id)\nFile \"/opt/stack/new/python-novaclient/novaclient/v1_1/servers.py\", line 555, in get\nreturn self._get(\"/servers/%s\" % base.getid(server), \"server\")\nFile \"/opt/stack/new/python-novaclient/novaclient/base.py\", line 93, in _get\n_resp, body = self.api.client.get(url)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 487, in get\nreturn self._cs_request(url, 'GET', **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 465, in _cs_request\nresp, body = self._time_request(url, method, **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 439, in _time_request\nresp, body = self.request(url, method, **kwargs)\nFile \"/opt/stack/new/python-novaclient/novaclient/client.py\", line 433, in request\nraise exceptions.from_response(resp, body, url, method)\n ClientException: The server has either erred or is incapable of performing the requested operation. (HTTP 500) (Request-ID: req-7d7ab999-1351-43be-bd51-96a100a7cdeb)\n\nTraceback (most recent call last):\nStringException: Empty attachments:\nstderr\nstdout", 
            "date_created": "2014-08-29 14:05:28.336445+00:00", 
            "author": "https://api.launchpad.net/1.0/~abhishek-kekane"
        }, 
        {
            "content": "Do you have a link to the logs from this run?", 
            "date_created": "2014-08-29 19:10:53.475347+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "I just found it: http://logs.openstack.org/37/98737/18/gate/gate-tempest-dsvm-neutron-full/1adef2a/console.html", 
            "date_created": "2014-08-29 19:11:37.873651+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "It looks like this is from neutron-server hanging: http://logs.openstack.org/37/98737/18/gate/gate-tempest-dsvm-neutron-full/1adef2a/logs/screen-n-api.txt.gz?level=INFO#_2014-08-29_13_03_38_109\n\nhttp://logs.openstack.org/37/98737/18/gate/gate-tempest-dsvm-neutron-full/1adef2a/logs/screen-q-svc.txt.gz?level=TRACE#_2014-08-29_13_03_59_833", 
            "date_created": "2014-08-30 01:28:32.864143+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "2014-08-29 13:03:59.833 740 TRACE oslo.messaging.rpc.dispatcher     raise operational_error\n2014-08-29 13:03:59.833 740 TRACE oslo.messaging.rpc.dispatcher OperationalError: (OperationalError) (1205, 'Lock wait timeout exceeded; try restarting transaction') 'INSERT INTO routerl3agentbindings (router_id, l3_agent_id) VALUES (%s, %s)' ('1f24da95-56d3-4393-9931-7121e484206c', 'b7207ce5-504d-47dd-be16-0ccef99c37ef')\n2014-08-29 13:03:59.833 740 TRACE oslo.messaging.rpc.dispatcher ", 
            "date_created": "2014-08-30 01:29:47.575328+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "This is causing neutron-server to hang and block on incoming API calls\n", 
            "date_created": "2014-08-30 01:32:38.103466+00:00", 
            "author": "https://api.launchpad.net/1.0/~jogo"
        }, 
        {
            "content": "Interesting...this was also observed while testing DVR (report available [1]). Bug #1356121 has been addressed by skipping auto scheduling altogether, but I am not sure the same fix is applicable in the context of centralized routers.\n\n[1] - https://bugs.launchpad.net/neutron/+bug/1356121", 
            "date_created": "2014-08-30 05:22:56.217308+00:00", 
            "author": "https://api.launchpad.net/1.0/~armando-migliaccio"
        }, 
        {
            "content": "http://logstash.openstack.org/#eyJzZWFyY2giOiJtZXNzYWdlOlwiaW4gYXV0b19zY2hlZHVsZV9yb3V0ZXJzXCIgYW5kIG1lc3NhZ2U6XCJPcGVyYXRpb25hbEVycm9yOiAoT3BlcmF0aW9uYWxFcnJvcilcIiBBTkQgZmlsZW5hbWU6XCJsb2dzL3NjcmVlbi1xLXN2Yy50eHRcIiAiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6ImFsbCIsImdyYXBobW9kZSI6ImNvdW50IiwidGltZSI6eyJ1c2VyX2ludGVydmFsIjowfSwic3RhbXAiOjE0MDkzNzY1NDI5OTAsIm1vZGUiOiIiLCJhbmFseXplX2ZpZWxkIjoiIn0=", 
            "date_created": "2014-08-30 05:29:27.489940+00:00", 
            "author": "https://api.launchpad.net/1.0/~armando-migliaccio"
        }, 
        {
            "content": "http://logstash.openstack.org/#eyJzZWFyY2giOiJtZXNzYWdlOlwiaW4gYXV0b19zY2hlZHVsZV9yb3V0ZXJzXCIgQU5EIG1lc3NhZ2U6XCJPcGVyYXRpb25hbEVycm9yOiAoT3BlcmF0aW9uYWxFcnJvcilcIiBBTkQgZmlsZW5hbWU6XCJsb2dzL3NjcmVlbi1xLXN2Yy50eHRcIiAiLCJmaWVsZHMiOltdLCJvZmZzZXQiOjAsInRpbWVmcmFtZSI6ImFsbCIsImdyYXBobW9kZSI6ImNvdW50IiwidGltZSI6eyJmcm9tIjoiMjAxNC0wOC0yOVQwNzo0Nzo1NyswMDowMCIsInRvIjoiMjAxNC0wOC0yOVQwNzo1NDoyOSswMDowMCIsInVzZXJfaW50ZXJ2YWwiOiIwIn0sInN0YW1wIjoxNDA5Mzc2OTk4MzczLCJtb2RlIjoiIiwiYW5hbHl6ZV9maWVsZCI6IiJ9", 
            "date_created": "2014-08-30 05:41:16.199750+00:00", 
            "author": "https://api.launchpad.net/1.0/~armando-migliaccio"
        }, 
        {
            "content": "Marking as Incomplete. No hits for quite a while.", 
            "date_created": "2014-11-21 09:39:30.199964+00:00", 
            "author": "https://api.launchpad.net/1.0/~enikanorov"
        }, 
        {
            "content": "[Expired for neutron because there has been no activity for 60 days.]", 
            "date_created": "2015-01-21 04:17:19.067425+00:00", 
            "author": "https://api.launchpad.net/1.0/~janitor"
        }
    ]
}