{
    "status": "Invalid", 
    "last_updated": "2012-03-19 14:48:37.079368+00:00", 
    "description": "\nI have a  devstack installation. 'nova-manage drive list'  and 'nova-manage help drive'  cmds are failing\n\n\ndeepak@deepak-app:/opt/stack/quantum/etc$ nova-manage drive list\n2012-03-19 16:12:30 CRITICAL nova [req-6e817710-6282-41f9-b4fa-7d5dcecfc30e None None] 'bool' object has no attribute 'decode'\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"/usr/local/bin/nova-manage\", line 7, in <module>\n(nova): TRACE:     execfile(__file__)\n(nova): TRACE:   File \"/opt/stack/nova/bin/nova-manage\", line 2207, in <module>\n(nova): TRACE:     main()\n(nova): TRACE:   File \"/opt/stack/nova/bin/nova-manage\", line 2188, in main\n(nova): TRACE:     fn_kwargs[k] = v.decode('utf-8')\n(nova): TRACE: AttributeError: 'bool' object has no attribute 'decode'\n(nova): TRACE: \ndeepak@deepak-app:/opt/stack/quantum/etc$ nova-manage help drive\nhelp does not match any options:\n\taccount\n\tagent\n\tconfig\n\tdb\n\tdrive\n\texport\n\tfixed\n\tflavor\n\tfloating\n\thost\n\tinstance_type\n\tnetwork\n\tproject\n\trole\n\tservice\n\tshell\n\tsm\n\tuser\n\tversion\n\tvm\n\tvolume\n\tvpn\n\tvsa\n\tlogs", 
    "tags": [], 
    "importance": "Undecided", 
    "heat": 6, 
    "link": "https://bugs.launchpad.net/nova/+bug/959176", 
    "owner": "None", 
    "id": 959176, 
    "index": 2705, 
    "created": "2012-03-19 10:46:59.180273+00:00", 
    "title": "'nova-manage drive'  cmd errors", 
    "comments": [
        {
            "content": "\nI have a  devstack installation. 'nova-manage drive list'  and 'nova-manage help drive'  cmds are failing\n\n\ndeepak@deepak-app:/opt/stack/quantum/etc$ nova-manage drive list\n2012-03-19 16:12:30 CRITICAL nova [req-6e817710-6282-41f9-b4fa-7d5dcecfc30e None None] 'bool' object has no attribute 'decode'\n(nova): TRACE: Traceback (most recent call last):\n(nova): TRACE:   File \"/usr/local/bin/nova-manage\", line 7, in <module>\n(nova): TRACE:     execfile(__file__)\n(nova): TRACE:   File \"/opt/stack/nova/bin/nova-manage\", line 2207, in <module>\n(nova): TRACE:     main()\n(nova): TRACE:   File \"/opt/stack/nova/bin/nova-manage\", line 2188, in main\n(nova): TRACE:     fn_kwargs[k] = v.decode('utf-8')\n(nova): TRACE: AttributeError: 'bool' object has no attribute 'decode'\n(nova): TRACE: \ndeepak@deepak-app:/opt/stack/quantum/etc$ nova-manage help drive\nhelp does not match any options:\n\taccount\n\tagent\n\tconfig\n\tdb\n\tdrive\n\texport\n\tfixed\n\tflavor\n\tfloating\n\thost\n\tinstance_type\n\tnetwork\n\tproject\n\trole\n\tservice\n\tshell\n\tsm\n\tuser\n\tversion\n\tvm\n\tvolume\n\tvpn\n\tvsa\n\tlogs", 
            "date_created": "2012-03-19 10:46:59.180273+00:00", 
            "author": "https://api.launchpad.net/1.0/~deepak.garg"
        }, 
        {
            "content": "The 'drive' command no longer exists. ", 
            "date_created": "2012-03-19 14:48:36.038835+00:00", 
            "author": "https://api.launchpad.net/1.0/~bcwaldon"
        }
    ]
}